from collections import OrderedDict

company_dict = OrderedDict([
    ("https://www.jobplanet.co.kr/companies/42217/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "네이버"),
    ("https://www.jobplanet.co.kr/companies/67099/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주) 안랩"),
    ("https://www.jobplanet.co.kr/companies/50992/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "㈜티맥스소프트"),
    ("https://www.jobplanet.co.kr/companies/53191/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "㈜KT"),
    ("https://www.jobplanet.co.kr/companies/1306/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "현대오토에버㈜"),
    ("https://www.jobplanet.co.kr/companies/20575/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "SK텔레콤"),
    ("https://www.jobplanet.co.kr/companies/30162/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "삼성에스디에스"),
    ("https://www.jobplanet.co.kr/companies/88463/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "엔에이치엔"),
    ("https://www.jobplanet.co.kr/companies/64418/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "엔씨소프트"),
    ("https://www.jobplanet.co.kr/companies/3386/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "한국아이비엠"),
    ("https://www.jobplanet.co.kr/companies/63859/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "LG CNS"),
    ("https://www.jobplanet.co.kr/companies/93880/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)카카오"),
    ("https://www.jobplanet.co.kr/companies/50695/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "티몬"),
    ("https://www.jobplanet.co.kr/companies/60632/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "위메프"),
    ("https://www.jobplanet.co.kr/companies/63857/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)엘지유플러스"),
    ("https://www.jobplanet.co.kr/companies/81407/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)더존비즈온"),
    ("https://www.jobplanet.co.kr/companies/285/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "효성아이티엑스(주)"),
    ("https://www.jobplanet.co.kr/companies/53174/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)케이티씨에스"),
    ("https://www.jobplanet.co.kr/companies/35657/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "롯데이노베이트(주)"),
    ("https://www.jobplanet.co.kr/companies/23717/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "카페24(주)"),
    ("https://www.jobplanet.co.kr/companies/89637/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)야놀자"),
    ("https://www.jobplanet.co.kr/companies/94863/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "씨제이올리브네트웍스(주)"),
    ("https://www.jobplanet.co.kr/companies/58985/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)지마켓"),
    ("https://www.jobplanet.co.kr/companies/88549/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "요기요"),
    ("https://www.jobplanet.co.kr/companies/20564/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "에스케이플래닛(주)"),
    ("https://www.jobplanet.co.kr/companies/83498/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)넥슨코리아"),
    ("https://www.jobplanet.co.kr/companies/96821/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)인라이플"),
    ("https://www.jobplanet.co.kr/companies/74164/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)사람인"),
    ("https://www.jobplanet.co.kr/companies/61420/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)우아한형제들"),
    ("https://www.jobplanet.co.kr/companies/7468/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)케이티알파"),
    ("https://www.jobplanet.co.kr/companies/76814/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)미라콤아이앤씨"),
    ("https://www.jobplanet.co.kr/companies/59375/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)이글루코퍼레이션"),
    ("https://www.jobplanet.co.kr/companies/53189/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)케이티디에스"),
    ("https://www.jobplanet.co.kr/companies/52955/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)코리아센터"),
    ("https://www.jobplanet.co.kr/companies/69740/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)신한디에스"),
    ("https://www.jobplanet.co.kr/companies/89255/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "라인플러스(주)"),
    ("https://www.jobplanet.co.kr/companies/311092/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)브랜디"),
    ("https://www.jobplanet.co.kr/companies/57278/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "잡코리아 유한책임회사"),
    ("https://www.jobplanet.co.kr/companies/82999/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)커넥트웨이브"),
    ("https://www.jobplanet.co.kr/companies/2065/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "한전케이디엔(주)"),
    ("https://www.jobplanet.co.kr/companies/20613/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "에스케이(주)"),
    ("https://www.jobplanet.co.kr/companies/78090/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)마이다스아이티"),
    ("https://www.jobplanet.co.kr/companies/82790/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)다우기술"),
    ("https://www.jobplanet.co.kr/companies/89314/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)스펙업애드"),
    ("https://www.jobplanet.co.kr/companies/19363/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "에스케이엠앤서비스(주)"),
    ("https://www.jobplanet.co.kr/companies/42722/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "나이스평가정보(주)"),
    ("https://www.jobplanet.co.kr/companies/337441/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "롯데쇼핑(주) e커머스사업본부"),
    ("https://www.jobplanet.co.kr/companies/53778/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)컴투스"),
    ("https://www.jobplanet.co.kr/companies/90398/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "휴넷(주)"),
    ("https://www.jobplanet.co.kr/companies/60656/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "여기어때"),
    ("https://www.jobplanet.co.kr/companies/55388/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)지에스아이티엠"),
    ("https://www.jobplanet.co.kr/companies/311572/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)디케이테크인"),
    ("https://www.jobplanet.co.kr/companies/50946/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "티시스(주)"),
    ("https://www.jobplanet.co.kr/companies/94249/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)비즈테크아이"),
    ("https://www.jobplanet.co.kr/companies/83745/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)네오위즈"),
    ("https://www.jobplanet.co.kr/companies/70072/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "신세계아이앤씨(주)"),
    ("https://www.jobplanet.co.kr/companies/19802/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "엔테크서비스(주)"),
    ("https://www.jobplanet.co.kr/companies/34778/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "메가존(주)"),
    ("https://www.jobplanet.co.kr/companies/67144/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "SOOP"),
    ("https://www.jobplanet.co.kr/companies/13637/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)현대이지웰"),
    ("https://www.jobplanet.co.kr/companies/60502/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)윈스"),
    ("https://www.jobplanet.co.kr/companies/9814/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "지오시스(유)"),
    ("https://www.jobplanet.co.kr/companies/7419/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "코나아이(주)"),
    ("https://www.jobplanet.co.kr/companies/332116/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)써머스플랫폼"),
    ("https://www.jobplanet.co.kr/companies/8893/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)직방"),
    ("https://www.jobplanet.co.kr/companies/78633/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)롯데닷컴"),
    ("https://www.jobplanet.co.kr/companies/61867/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)와이즈넛"),
    ("https://www.jobplanet.co.kr/companies/20582/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "에스케이커뮤니케이션즈(주)"),
    ("https://www.jobplanet.co.kr/companies/53227/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "케이지이니시스(주)"),
    ("https://www.jobplanet.co.kr/companies/90036/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "(주)미디어로그"),
    ("https://www.jobplanet.co.kr/companies/18046/interviews_by_filter?by_occupation=11600&by_job_rank=&by_success=&page=", "예스이십사(주)")
])
